version: '3.8'

services:
  loginsite-db:
    image: quay.io/aleksander124/loginsite-db:v2
    container_name: loginsite-db
    networks:
      - loginsite
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  loginsite-front:
    image: quay.io/aleksander124/loginsite-front:v2
    container_name: loginsite-front
    networks:
      - loginsite
      - traefik-network
    ports:
      - "8090:8090"
    environment:
      DB_HOST: loginsite-db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: logowanie
    labels:
      - "traefik.enable=true"

  loginsite-api:
    image: quay.io/aleksander124/loginsite-api:20240804.183337
    container_name: loginsite-api
    networks:
      - loginsite
      - traefik-network
    ports:
      - "9100:9100"
    environment:
      DATABASE_HOSTNAME: loginsite-db
#      DATABASE_USER: root
#      DATABASE_PASSWORD: root
#      DATABASE_NAME: logowanie
#      DATABASE_PORT: 3306
    labels:
      - "traefik.enable=true"
    depends_on:
      - loginsite-db

networks:
  loginsite:
    external: true
  traefik-network:
    external: true