name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  QUAY_REGISTRY: quay.io
  IMAGE_TAG: v1-pdo

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.QUAY_REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build and push Docker image for loginsite-front
        run: |
          docker build -t ${{ env.QUAY_REGISTRY }}/aleksander124/loginsite-front:${{ env.IMAGE_TAG }} -f loginsite-front/Dockerfile loginsite-front
          docker push ${{ env.QUAY_REGISTRY }}/aleksander124/loginsite-front:${{ env.IMAGE_TAG }}

      # Build and push the Docker image for loginsite-db
      - name: Build and push Docker image for loginsite-db
        run: |
          docker build -t ${{ env.QUAY_REGISTRY }}/aleksander124/loginsite-db:${{ env.IMAGE_TAG }} -f loginsite-db/Dockerfile loginsite-db
          docker push ${{ env.QUAY_REGISTRY }}/aleksander124/loginsite-db:${{ env.IMAGE_TAG }}
